### ISSUE TITLE
Latest Version

### ISSUE THREAD

**Issue by cemozguraA** [DamianSuess/Test.FloatingActionButton#1]
Firstly, thank you. I pulled the library to the latest version on Android and Forms. I created a new example and added the LongClick prop.

**Comment by DamianSuess** [comment]
@cemozguraA Wonderful, feel free to create a PR if there's any major overhauling changes & I'll merge it in. 

Happy that we got to chat on the forums and you've found this sample project useful

**Comment by DamianSuess** [comment]
@cemozguraA Thanks again for reaching out a while back. It's not often that an author updates the folks using their packages with changes.

I updated this MVVM sample to your latest package.  It's running great!
